### ISSUE TITLE
[FOR-31] Change the footer link and text.

### ISSUE THREAD

**Issue by punithraj06** [formzillion/formzillion.com#146]
Change the redirection url in the footer of [formId]/settings/thank-you-page to "[docs-domain]/features/thank-you-page" and also url text to "Thank you page".  Change the page title to "Thank you page" 
![image](https://github.com/formzillion/formzillion.com/assets/99784529/bb999c8d-19bb-4971-82d1-15ee0019d0df)

<sub>[FOR-31](https://linear.app/zillionstack/issue/FOR-31/change-the-footer-link-and-text)</sub>

**Comment by JaiS99** [comment]
is this open to be assigned?, if yes please assign me, what branch are we looking to fix this on?
