### ISSUE TITLE
[FZ-39] Create See it in Action section

### ISSUE THREAD

**Issue by HarshShahDev** [formzillion/formzillion.com#147]
We have to create a "See it in Action" section below the Hero Section of the page.

![](https://uploads.linear.app/1b81e042-d19f-4105-b528-e295c6f43a3f/5c26b43f-b345-49be-9539-c25ce67a9446/1899a952-595e-40aa-acb6-b5a0630e8909)

Something similar to the Features section with tabbed layout, so that we have more than one usecase demo section. For example:

1. Personal Blog - Newsletter Form
2. Agency Website - Request Quotation Form
3. Agency Website - Contact Us Form

<sub>From [SyncLinear.com](https://synclinear.com) | [FZ-39](https://linear.app/zillionstack/issue/FZ-39/create-see-it-in-action-section)</sub>

**Comment by HarshShahDev** [comment]
This section will give user an idea how to create form with quick demo

**Comment by Thirunavukkarasu** [comment]
@harsh.shah I updated the description, please do check the same.
