### ISSUE TITLE
Mailerlite Integration

### ISSUE THREAD

**Issue by AbdulWadudh** [formzillion/formzillion.com#3]
Integrate your forms with Mailerlite, a feature-rich email marketing platform. Automatically add new form submissions to your mailing lists, send personalized email campaigns, and engage with your subscribers effortlessly. Nurture leads and build strong customer relationships with ease.

https://dev-docs.formzillion.com/integrations/mailerlite

**Comment by Thirunavukkarasu** [comment]
@AbdulWadudh update the docs url in the description as well.
